
local settings = {
	{
		name = "trim-enabled",
		type = "bool-setting",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "a",
	},
	{
		name = "stack-trimming-threshold",
		type = "double-setting",
		setting_type = "runtime-per-user",
		default_value = 0.2,
		minimum_value = 0,
		maximum_value = 1,
		order = "b1",
	},
	{
		name = "notification-flying-text-enabled",
		type = "bool-setting",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "b2",
	},
	{
		name = "inventory-slots-used-trimming-active-threshold",
		type = "double-setting",
		setting_type = "runtime-per-user",
		default_value = 0.6,
		minimum_value = 0,
		maximum_value = 1,
		order = "c",
	},
	{
		name = "inventory-slots-keep-free",
		type = "int-setting",
		setting_type = "runtime-per-user",
		default_value = 10,
		minimum_value = 0,
		hidden = true,
		order = "c1",
	},
	{
		name = "inventory-slots-aggressively-keep-free",
		type = "int-setting",
		setting_type = "runtime-per-user",
		default_value = 3,
		minimum_value = 0,
		hidden = true,
		order = "c2",
	},
	{
		name = "trim-unhealthy-items-first",
		type = "bool-setting",
		setting_type = "runtime-per-user",
		default_value = true,
		hidden = true,
		order = "c3",
	},
	{
		name = "pickup-margin",
		type = "double-setting",
		setting_type = "runtime-per-user",
		default_value = 0.1,
		minimum_value = 0,
		maximum_value = 0.4,
		hidden = true,
		order = "c4",
	},
}

data:extend(settings)
